package util;

public class Agreements {
	public static final int MESSAGE = 1;
	public static final int FILE = 2;
	public static final int ID_PASSWORD = 3;
	public static final int USER = 4;
	public static final int USER_PASS = 5;
	public static final int USER_SHUT = 6;
	public static final int haveOnline = 7;
	public static final int ADD_FRIENDS = 8;
	public static final int NOT_HAVETHISUSER = 9;
	public static final int YES_HAVETHISUSER = 10;
	public static final int BUILD_FRIEND = 11;
	public static final int DELETE_REQUEST = 12;
	public static final int ADD_REQUEST = 13;
	public static final int UPDATA_FRIENDS = 14;
	public static final int UPDATA_REMARK = 15;
	public static final int ADD_USER = 16;
	public static final int WINTOADD = 17;
	public static final int LOSETOADD = 19;
	public static final int FILE_MESSAGE = 20;
	public static final int GET_FILE = 21;
	public static final int NOT_GET_FILE = 22;
	public static final int DELETE_FRIEND = 23;
	public static final int DELETE_DIALOGUE = 24;
	public static final int UPDATA_USER = 25;
	public static final int ADD_DIALOGUE = 26;
	public static final int SEND_ERROR = 27;
	public static final int GET_GROUPS = 28;
	public static final int GET_MEMBERS = 29;
	public static final int SEND_GROUP_MESSAGE = 30;
	public static final int GROUP_INVITE = 31;
	public static final int GROUP_DELETE = 32;
	public static final int CHANGE_GROUP_NAME = 33;
	public static final int UPDATE_NEW_GROUP = 34;
	public static final int BUILD_GROUP = 35;
	public static final int BUILF_GROUP_SECCESS = 36;
	public static final int BUILE_GROUP_LOSE = 37;
	public static final int RESTART_DELAYED = 38;
	public static final int CLOSE = 99;
}
